import { ShieldCheck, Trash2 } from 'lucide-react';
import { FormEvent, useState } from 'react';
import styled from 'styled-components';
import { Button, EmptyState, ErrorState, Field, InlineForm, LoadingState, Page, PageHeader, Surface } from '../components/ui';
import { useChangeAccessMutation, useGrantAccessMutation, useProjectAccessQuery, useProjectsQuery, useRemoveAccessMutation, useUsersQuery } from '../features/api/api';
import { roleLabel } from '../utils/format';

const AccessList=styled(Surface)`>div{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:17px 20px;border-top:1px solid var(--line)}>div:first-child{border-top:0}strong{display:block}span{font-size:.8rem;color:var(--muted)}`;
export function AdminAccessPage(){const {data:projects,isLoading:pLoading}=useProjectsQuery(true);const {data:users,isLoading:uLoading}=useUsersQuery();const [projectId,setProjectId]=useState('');const [userId,setUserId]=useState('');const [permission,setPermission]=useState('VIEW');const {data:access,isLoading:aLoading,isError}=useProjectAccessQuery(projectId,{skip:!projectId});const [grant,{isLoading:saving,error:grantError}]=useGrantAccessMutation();const [change]=useChangeAccessMutation();const [remove]=useRemoveAccessMutation();if(pLoading||uLoading)return <Page><LoadingState/></Page>;const selectedProject=projects?.data.find(p=>p.id===projectId);const eligible=users?.data.filter(u=>u.status==='ACTIVE'&&u.id!==selectedProject?.ownerId&&!access?.accesses.some(a=>a.user.id===u.id))??[];const submit=async(e:FormEvent)=>{e.preventDefault();if(projectId&&userId){await grant({projectId,userId,permission});setUserId('')}};const revoke=async(accessId:string)=>{if(window.confirm('Remover este acesso compartilhado?'))await remove({projectId,accessId})};return <Page><PageHeader><div><h1>Acessos às obras</h1><p>Conceda visualização ou edição obra por obra.</p></div></PageHeader><Field style={{maxWidth:560,marginBottom:24}}>Selecione uma obra<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Escolha uma obra</option>{projects?.data.map(p=><option key={p.id} value={p.id}>{p.name} — {p.owner.name}</option>)}</select></Field>{!projectId?<EmptyState title="Nenhuma obra selecionada">Selecione uma obra para consultar e administrar seus acessos.</EmptyState>:aLoading?<LoadingState/>:isError||!access?<ErrorState/>:<><AccessList><div><span><strong>{access.owner.name}</strong>{access.owner.email} · proprietário</span><ShieldCheck color="var(--teal)"/></div>{access.accesses.map(a=><div key={a.id}><span><strong>{a.user.name}</strong>{a.user.email} · {roleLabel[a.user.role]}</span><span style={{display:'flex',alignItems:'center',gap:8}}><select value={a.permission} onChange={e=>change({projectId,accessId:a.id,permission:e.target.value})} aria-label={`Permissão de ${a.user.name}`}><option value="VIEW">Visualização</option><option value="EDIT">Edição</option></select><Button $variant="danger" onClick={()=>revoke(a.id)}><Trash2 size={16}/>Remover</Button></span></div>)}</AccessList><InlineForm onSubmit={submit} style={{marginTop:24}}><Field>Usuário<select value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Selecione</option>{eligible.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field>Permissão<select value={permission} onChange={e=>setPermission(e.target.value)}><option value="VIEW">Somente visualização</option><option value="EDIT">Pode editar</option></select></Field><Button disabled={!userId||saving}>Conceder acesso</Button></InlineForm>{grantError&&<p style={{color:'var(--danger)'}}>Não foi possível conceder o acesso.</p>}</>}</Page>}
