import { zodResolver } from '@hookform/resolvers/zod';
import { Plus, Power } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Badge, Button, DialogShell, EmptyState, ErrorState, Field, FormGrid, LoadingState, Page, PageHeader, Table, TableWrap } from '../components/ui';
import { useCreateUserMutation, useSetUserStatusMutation, useUsersQuery } from '../features/api/api';
import { formatDate, roleLabel } from '../utils/format';

const schema=z.object({name:z.string().min(3),email:z.string().email(),password:z.string().min(8),role:z.enum(['ADMIN','MANAGER','VIEWER'])});type Data=z.infer<typeof schema>;
export function AdminUsersPage(){const {data,isLoading,isError}=useUsersQuery();const [open,setOpen]=useState(false);const [status,{isLoading:changing}]=useSetUserStatusMutation();if(isLoading)return <Page><LoadingState/></Page>;if(isError)return <Page><ErrorState/></Page>;const users=data?.data??[];const toggle=async(id:string,current:string)=>{if(window.confirm(`${current==='ACTIVE'?'Desativar':'Ativar'} este usuário?`))await status({id,status:current==='ACTIVE'?'INACTIVE':'ACTIVE'})};return <Page><PageHeader><div><h1>Usuários</h1><p>Contas criadas pela administração e seus níveis de acesso.</p></div><Button onClick={()=>setOpen(true)}><Plus size={17}/>Novo usuário</Button></PageHeader>{users.length?<TableWrap><Table><thead><tr><th>Usuário</th><th>Perfil</th><th>Status</th><th>Obras próprias</th><th>Compartilhadas</th><th>Criado em</th><th>Ações</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><br/><small>{u.email}</small></td><td>{roleLabel[u.role]}</td><td><Badge $tone={u.status==='ACTIVE'?'success':'danger'}>{u.status==='ACTIVE'?'Ativo':'Inativo'}</Badge></td><td>{u._count?.ownedProjects??0}</td><td>{u._count?.projectAccesses??0}</td><td>{formatDate(u.createdAt)}</td><td><Button $variant={u.status==='ACTIVE'?'danger':'secondary'} disabled={changing} onClick={()=>toggle(u.id,u.status)}><Power size={15}/>{u.status==='ACTIVE'?'Desativar':'Ativar'}</Button></td></tr>)}</tbody></Table></TableWrap>:<EmptyState title="Nenhum usuário">Crie a primeira conta operacional.</EmptyState>}{open&&<UserDialog close={()=>setOpen(false)}/>}</Page>}
function UserDialog({close}:{close:()=>void}){const [create,{isLoading,error}]=useCreateUserMutation();const {register,handleSubmit,formState:{errors}}=useForm<Data>({resolver:zodResolver(schema),defaultValues:{role:'MANAGER'}});const submit=async(data:Data)=>{try{await create(data).unwrap();close()}catch{/* exibido */}};return <DialogShell title="Novo usuário" close={close}><form onSubmit={handleSubmit(submit)}><FormGrid><Field>Nome<input {...register('name')}/>{errors.name&&<em>Informe o nome completo.</em>}</Field><Field>E-mail<input type="email" {...register('email')}/>{errors.email&&<em>E-mail inválido.</em>}</Field><Field>Senha inicial<input type="password" {...register('password')}/>{errors.password&&<em>Mínimo de 8 caracteres.</em>}</Field><Field>Perfil<select {...register('role')}><option value="MANAGER">Gestor</option><option value="VIEWER">Visualizador</option><option value="ADMIN">Administrador</option></select></Field></FormGrid>{error&&<p style={{color:'var(--danger)'}}>Não foi possível criar. O e-mail pode já estar em uso.</p>}<Button $wide style={{marginTop:22}} disabled={isLoading}>Criar usuário</Button></form></DialogShell>}
